# Generated by Django 4.2 on 2023-05-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='telephone',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='datum',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='produkt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='quelle',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='score',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='status',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='telefon',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
