# Generated by Django 4.2 on 2023-05-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_dashboard_telephone_dashboard_datum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='datum',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='quelle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='telefon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
