# Generated by Django 4.2 on 2023-05-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_dashboard_datum_alter_dashboard_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='name',
            field=models.TextField(default='none'),
        ),
    ]
