# Generated by Django 4.2 on 2023-05-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_dashboard_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='email',
            field=models.EmailField(default='ra@gmail.com', max_length=254),
        ),
    ]
