# Generated by Django 4.2 on 2023-05-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_dashboard_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='produkt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='score',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
