# Generated by Django 4.2 on 2023-07-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_dashboard_produkt_alter_dashboard_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='email_view',
            field=models.TextField(blank=True, null=True),
        ),
    ]
