# Generated by Django 4.2 on 2023-07-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_dashboard_email_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='email_view',
            field=models.TextField(blank=True, default=''),
        ),
    ]
